version: "3"
services:
  sn-node:
    image: ghcr.io/scrtlabs/localsecret:v1.3.1
    networks:
      - default
    ports:
      - "26657:26657"
      - "9091:9091"
      - "1317:1317"
      - "5001:5001"
  bitcoin:
    build: docker/bitcoin
    networks:
      - default
    ports:
      - "8080:8080"
      - "18445:18444"
networks:
  default:
    name: sbtc_local
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
