# Based on https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml

name: Contracts

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "contracts/**/*"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "contracts/**/*"

jobs:
  gateway-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/gateway/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/gateway/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/gateway/Cargo.toml

      - name: Optimize contract.wasm
        working-directory: ./contracts/gateway
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/gateway/contract.wasm optimization
          add: contracts/gateway/contract.wasm

  gateway-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=contracts/gateway/Cargo.toml -- --check --config-path=contracts/gateway/rustfmt.toml

  bitcoin-spv-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/bitcoin_spv/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/bitcoin_spv/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/bitcoin_spv/Cargo.toml

      - name: Optimize contract.wasm
        working-directory: ./contracts/bitcoin_spv
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/bitcoin_spv/contract.wasm optimization
          add: contracts/bitcoin_spv/contract.wasm

  bitcoin-spv-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=contracts/bitcoin_spv/Cargo.toml -- --check --config-path=contracts/bitcoin_spv/rustfmt.toml

  multisig-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/multisig/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/multisig/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/multisig/Cargo.toml
      
      - name: Optimize contract.wasm
        working-directory: ./contracts/multisig
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/multisig/contract.wasm optimization
          add: contracts/multisig/contract.wasm

  multisig-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path=contracts/multisig/Cargo.toml -- --check --config-path=contracts/multisig/rustfmt.toml

  sfps-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/sfps/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/sfps/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/sfps/Cargo.toml

      - name: Optimize contract.wasm
        working-directory: ./contracts/sfps
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/sfps/contract.wasm optimization
          add: contracts/sfps/contract.wasm

  sfps-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=contracts/sfps/Cargo.toml -- --check --config-path=contracts/sfps/rustfmt.toml

  shuriken-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/shuriken/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/shuriken/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/shuriken/Cargo.toml

      - name: Optimize contract.wasm
        working-directory: ./contracts/shuriken
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/shuriken/contract.wasm optimization
          add: contracts/shuriken/contract.wasm

  shuriken-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=contracts/shuriken/Cargo.toml -- --check --config-path=contracts/shuriken/rustfmt.toml

  log-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/log/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/log/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/log/Cargo.toml

      - name: Optimize contract.wasm
        working-directory: ./contracts/log
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/log/contract.wasm optimization
          add: contracts/log/contract.wasm

  log-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=contracts/log/Cargo.toml -- --check --config-path=contracts/log/rustfmt.toml

  vesting-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/vesting/Cargo.toml
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown --locked --manifest-path=contracts/vesting/Cargo.toml
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Generate Schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example schema --locked --manifest-path=contracts/vesting/Cargo.toml

      - name: Optimize contract.wasm
        working-directory: ./contracts/vesting
        run: npx -y -- wasm-opt -Os ./target/wasm32-unknown-unknown/release/*.wasm -o ./contract.wasm

      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@v9
        with:
          message: Apply contracts/vesting/contract.wasm optimization
          add: contracts/vesting/contract.wasm

  vesting-lints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=contracts/vesting/Cargo.toml -- --check --config-path=contracts/vesting/rustfmt.toml

  bitcoin-header-chain-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/libs/bitcoin_header_chain/Cargo.toml
        env:
          RUST_BACKTRACE: 1

  pure-rust-bitcoin-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=contracts/libs/pure-rust-bitcoin/Cargo.toml
        env:
          RUST_BACKTRACE: 1

  sfps-lib-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.63.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --manifest-path=contracts/libs/sfps_lib/Cargo.toml
        env:
          RUST_BACKTRACE: 1
